services:
#    chec_reg.example:
#        class: Chec\RegBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
#services:
#    chec.reg.twig_extension:
#        class: Chec\RegBundle\Twig\TwigExtension
#        public: false
#        tags:
#             - { name: twig.extension }