chec_reg:
    resource: "@ChecRegBundle/Controller"
    type:     annotation

chec_user:
    resource: "@ChecUserBundle/Controller"
    type: annotation
#    prefix: /

login:
    pattern:   /login
    defaults:  { _controller: ChecSecurityBundle:Security:login }
login_check:
    pattern:   /login_check


#chec_user_user:
#    resource: "@ChecUserBundle/Controller/UserController.php"
#    type:     annotation

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
