chec_reg:
    resource: "@ChecRegBundle/Controller/"
    type:     annotation
    prefix:   /

chec_user_user:
    resource: "@ChecUserBundle/Controller/UserController.php"
    type:     annotation

rch_user:
    resource: "@ChecUserBundle/Controller"
    type: annotation
    prefix: /

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
