# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
services:
    chec.reg.twig_extension:
        class: Chec\RegBundle\Twig\TwigExtension
        public: false
        tags:
             - { name: twig.extension }
    chec.reg.util:
        class: Chec\RegBundle\Util\Util
